print("welcome to tip calculator!")
bill=float(input("what was the total bill? Rs."))
tip=int(input("what percentage tip would you like to give? 10 12 15"))
people=int(input("how many people to split the bill?"))
people_with_tip=bill*(1+tip/100)
print(people_with_tip)